### ISSUE TITLE
Application Icon Is the Windows default, Not Cut-It.  

### ISSUE THREAD

**Issue by adithyav2** [http-samc/cut-it#10]
Self-Explanatory (The version without the installer just the million files and app)(DW I'm testing both rn)

**Comment by http-samc** [comment]
This can't be fixed, it's a peril of using a modern window. For reference, cardr has the same issue. This should only be prevalent when you are mousing over the open window, the shortcut and the .exe icon (and the icon if you pin to taskbar) are all the logo.
