### ISSUE TITLE
When you hit ctrl+p, a little white box with your text shows up and disappears in 5 minutes. 

### ISSUE THREAD

**Issue by adithyav2** [http-samc/cut-it#11]

**Comment by http-samc** [comment]
That's the web browser that's saving your card, it's how we convert from html to PDF. This means the program is working. (Card is being saved in the dir selected) I might add in a "saving card" title bar to prevent confusion, but the message box also says "card saved" after

**Comment by http-samc** [comment]
not able to add in title bar due to lack of QtModern support. The message box notifies you that the PDF saving failed regardless so it really isn't a point of concern

**Comment by http-samc** [comment]
fixed by opening card in browser to show user that it was saved
