### ISSUE TITLE
In dark mode, the cite and tag text are hard to read through the highlight

### ISSUE THREAD

**Issue by adithyav2** [http-samc/cut-it#12]

**Comment by http-samc** [comment]
Yeah this is why I want to ship if with light mode by default. I might change only the evidence box to a lighter gray, not completely sure how to solve.

**Comment by adithyav2** [comment]
lighter great sounds good

**Comment by adithyav2** [comment]
grey*^

**Comment by http-samc** [comment]
not making much of a difference, fixing by changing default theme to light mode (that way more experienced users that can distinguish the difference can use it without discouraging new users
