### ISSUE TITLE
Sometimes the entire card text is the name of the card in card history. There has to be a way to rename cards if that error happens as well.

### ISSUE THREAD

**Issue by adithyav2** [http-samc/cut-it#18]

**Comment by http-samc** [comment]
This is so you can search the cards. Usually it goes [card number] [tag line if supplied] [text]. If no tag is supplied it'll only show the text. Maybe 1) calling tagline "card name" and/or 2) forcing users to enter one to save could solve?

**Comment by adithyav2** [comment]
ok it's fine as is but maybe a rename feature?

**Comment by http-samc** [comment]
I'll patch this by calling tagline card name (& updating tooltip) and requiring one to save to card history. The rename thing is an enhancement and won't be included in this bugfix patch

**Comment by http-samc** [comment]
You can just change the tag and the rename auto applies on restart
